spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api
  profiles:
    include: info
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  jwt:
    key: ${JWT_KEY}
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
springdoc:
  use-fqn: true