spring:
  application:
    name: api
  profiles:
    include: info
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  jwt:
    key: ${JWT_KEY}
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
springdoc:
  use-fqn: true